In [1]:
import numpy as np
np.linspace(-3,3)

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])

In [4]:
array= np.linspace(-3,3,num=100)
array+100

array([ 97.        ,  97.06060606,  97.12121212,  97.18181818,
        97.24242424,  97.3030303 ,  97.36363636,  97.42424242,
        97.48484848,  97.54545455,  97.60606061,  97.66666667,
        97.72727273,  97.78787879,  97.84848485,  97.90909091,
        97.96969697,  98.03030303,  98.09090909,  98.15151515,
        98.21212121,  98.27272727,  98.33333333,  98.39393939,
        98.45454545,  98.51515152,  98.57575758,  98.63636364,
        98.6969697 ,  98.75757576,  98.81818182,  98.87878788,
        98.93939394,  99.        ,  99.06060606,  99.12121212,
        99.18181818,  99.24242424,  99.3030303 ,  99.36363636,
        99.42424242,  99.48484848,  99.54545455,  99.60606061,
        99.66666667,  99.72727273,  99.78787879,  99.84848485,
        99.90909091,  99.96969697, 100.03030303, 100.09090909,
       100.15151515, 100.21212121, 100.27272727, 100.33333333,
       100.39393939, 100.45454545, 100.51515152, 100.57575758,
       100.63636364, 100.6969697 , 100.75757576, 100.81

In [5]:
np.random.randint(50,high=101,size=100)

array([54, 61, 79, 91, 81, 88, 73, 87, 92, 68])

In [10]:
np.random.randint(50,size=(50,5),high=100)

array([[58, 65, 57, 84, 53],
       [64, 77, 51, 55, 84],
       [79, 63, 66, 73, 99],
       [85, 94, 58, 81, 63],
       [79, 82, 92, 69, 95],
       [52, 70, 73, 51, 83],
       [76, 78, 67, 71, 51],
       [99, 53, 92, 63, 71],
       [67, 71, 77, 57, 74],
       [89, 52, 54, 67, 94],
       [60, 95, 89, 60, 58],
       [91, 66, 99, 59, 99],
       [63, 57, 67, 96, 62],
       [63, 76, 66, 94, 83],
       [70, 75, 54, 59, 60],
       [87, 53, 50, 81, 55],
       [91, 86, 82, 63, 88],
       [99, 55, 85, 95, 53],
       [52, 57, 97, 87, 63],
       [67, 56, 56, 80, 71],
       [66, 53, 56, 87, 98],
       [98, 64, 99, 72, 76],
       [85, 86, 76, 82, 95],
       [60, 65, 79, 73, 53],
       [78, 65, 70, 54, 86],
       [73, 97, 64, 92, 55],
       [70, 99, 72, 93, 64],
       [78, 67, 96, 70, 80],
       [77, 91, 92, 58, 60],
       [98, 60, 61, 59, 58],
       [95, 83, 70, 96, 70],
       [57, 68, 54, 79, 95],
       [73, 71, 76, 79, 75],
       [93, 96, 58, 71, 64],
       [99, 58